# Generated by Django 5.1 on 2024-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_author_book_genre_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
