from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views.bookViews import BookViewSet
from api.views.commentViews import CommentViewSet
from api.views.userViews import UserViewSet
from api.views.dummy_view import DummyVarView  # Import the DummyVarView

# Set up the router for the viewsets - the routes will be automatically generated by Django
router = DefaultRouter()
router.register(r'books', BookViewSet)
router.register(r'comments', CommentViewSet)
router.register(r'users', UserViewSet)

# Define the urlpatterns
urlpatterns = [
    path('api/', include(router.urls)),
    path('api/dummy/', DummyVarView.as_view(), name='dummy_var'),  # Add the custom route for DUMMY_VAR
]
